/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const field: string;
declare const input: string;
declare const inputLabel: string;
declare const inputErrors: string;

export {
	field,
	input,
	inputLabel,
	inputErrors
};

declare const __default_export__: {
	field: typeof field;
	input: typeof input;
	inputLabel: typeof inputLabel;
	inputErrors: typeof inputErrors;
};
export default __default_export__;
