/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const pageHeader: string;
declare const pageTitle: string;
declare const pageSubtitle: string;
declare const errorAlert: string;
declare const statsRow: string;
declare const statCard: string;
declare const statLabel: string;
declare const statValue: string;
declare const listCard: string;
declare const cardHeader: string;
declare const cardTitle: string;
declare const empty: string;
declare const tableScroll: string;
declare const table: string;
declare const rolePill: string;
declare const roleAdmin: string;
declare const roleTrader: string;
declare const numeric: string;
declare const emailCell: string;
declare const dateCell: string;
declare const actions: string;

export {
	container,
	pageHeader,
	pageTitle,
	pageSubtitle,
	errorAlert,
	statsRow,
	statCard,
	statLabel,
	statValue,
	listCard,
	cardHeader,
	cardTitle,
	empty,
	tableScroll,
	table,
	rolePill,
	roleAdmin,
	roleTrader,
	numeric,
	emailCell,
	dateCell,
	actions
};

declare const __default_export__: {
	container: typeof container;
	pageHeader: typeof pageHeader;
	pageTitle: typeof pageTitle;
	pageSubtitle: typeof pageSubtitle;
	errorAlert: typeof errorAlert;
	statsRow: typeof statsRow;
	statCard: typeof statCard;
	statLabel: typeof statLabel;
	statValue: typeof statValue;
	listCard: typeof listCard;
	cardHeader: typeof cardHeader;
	cardTitle: typeof cardTitle;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	table: typeof table;
	rolePill: typeof rolePill;
	roleAdmin: typeof roleAdmin;
	roleTrader: typeof roleTrader;
	numeric: typeof numeric;
	emailCell: typeof emailCell;
	dateCell: typeof dateCell;
	actions: typeof actions;
};
export default __default_export__;
