/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const priceCard: string;
declare const assetHeader: string;
declare const icon: string;
declare const assetIdentity: string;
declare const assetName: string;
declare const assetSymbol: string;
declare const description: string;
declare const priceBlock: string;
declare const priceLabel: string;
declare const price: string;
declare const changeBadge: string;
declare const positive: string;
declare const negative: string;
declare const arrow: string;
declare const changeAmount: string;
declare const rangeBlock: string;
declare const rangeHeader: string;
declare const rangeBoundsInline: string;
declare const rangeBar: string;
declare const rangeFill: string;
declare const rangeMarker: string;
declare const rangeBounds: string;
declare const statsGrid: string;
declare const statItem: string;
declare const statLabel: string;
declare const statValue: string;
declare const statPositive: string;
declare const statNegative: string;

export {
	priceCard,
	assetHeader,
	icon,
	assetIdentity,
	assetName,
	assetSymbol,
	description,
	priceBlock,
	priceLabel,
	price,
	changeBadge,
	positive,
	negative,
	arrow,
	changeAmount,
	rangeBlock,
	rangeHeader,
	rangeBoundsInline,
	rangeBar,
	rangeFill,
	rangeMarker,
	rangeBounds,
	statsGrid,
	statItem,
	statLabel,
	statValue,
	statPositive,
	statNegative
};

declare const __default_export__: {
	priceCard: typeof priceCard;
	assetHeader: typeof assetHeader;
	icon: typeof icon;
	assetIdentity: typeof assetIdentity;
	assetName: typeof assetName;
	assetSymbol: typeof assetSymbol;
	description: typeof description;
	priceBlock: typeof priceBlock;
	priceLabel: typeof priceLabel;
	price: typeof price;
	changeBadge: typeof changeBadge;
	positive: typeof positive;
	negative: typeof negative;
	arrow: typeof arrow;
	changeAmount: typeof changeAmount;
	rangeBlock: typeof rangeBlock;
	rangeHeader: typeof rangeHeader;
	rangeBoundsInline: typeof rangeBoundsInline;
	rangeBar: typeof rangeBar;
	rangeFill: typeof rangeFill;
	rangeMarker: typeof rangeMarker;
	rangeBounds: typeof rangeBounds;
	statsGrid: typeof statsGrid;
	statItem: typeof statItem;
	statLabel: typeof statLabel;
	statValue: typeof statValue;
	statPositive: typeof statPositive;
	statNegative: typeof statNegative;
};
export default __default_export__;
