/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const mainContainer: string;
declare const header: string;
declare const title: string;
declare const count: string;
declare const empty: string;
declare const tableScroll: string;
declare const table: string;
declare const typePill: string;
declare const typeBuy: string;
declare const typeSell: string;
declare const symbol: string;
declare const dateCell: string;

export {
	mainContainer,
	header,
	title,
	count,
	empty,
	tableScroll,
	table,
	typePill,
	typeBuy,
	typeSell,
	symbol,
	dateCell
};

declare const __default_export__: {
	mainContainer: typeof mainContainer;
	header: typeof header;
	title: typeof title;
	count: typeof count;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	table: typeof table;
	typePill: typeof typePill;
	typeBuy: typeof typeBuy;
	typeSell: typeof typeSell;
	symbol: typeof symbol;
	dateCell: typeof dateCell;
};
export default __default_export__;
