/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const pageHeader: string;
declare const pageTitle: string;
declare const pageSubtitle: string;
declare const errorAlert: string;
declare const formCard: string;
declare const listCard: string;
declare const cardTitle: string;
declare const cardHeader: string;
declare const cardCount: string;
declare const addForm: string;
declare const fieldGroup: string;
declare const fieldGrow: string;
declare const fieldLabel: string;
declare const select: string;
declare const submitButton: string;
declare const empty: string;
declare const tableScroll: string;
declare const table: string;
declare const symbolLink: string;
declare const numeric: string;
declare const changeBadge: string;
declare const positive: string;
declare const negative: string;
declare const notesCell: string;
declare const notesField: string;
declare const actions: string;

export {
	container,
	pageHeader,
	pageTitle,
	pageSubtitle,
	errorAlert,
	formCard,
	listCard,
	cardTitle,
	cardHeader,
	cardCount,
	addForm,
	fieldGroup,
	fieldGrow,
	fieldLabel,
	select,
	submitButton,
	empty,
	tableScroll,
	table,
	symbolLink,
	numeric,
	changeBadge,
	positive,
	negative,
	notesCell,
	notesField,
	actions
};

declare const __default_export__: {
	container: typeof container;
	pageHeader: typeof pageHeader;
	pageTitle: typeof pageTitle;
	pageSubtitle: typeof pageSubtitle;
	errorAlert: typeof errorAlert;
	formCard: typeof formCard;
	listCard: typeof listCard;
	cardTitle: typeof cardTitle;
	cardHeader: typeof cardHeader;
	cardCount: typeof cardCount;
	addForm: typeof addForm;
	fieldGroup: typeof fieldGroup;
	fieldGrow: typeof fieldGrow;
	fieldLabel: typeof fieldLabel;
	select: typeof select;
	submitButton: typeof submitButton;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	table: typeof table;
	symbolLink: typeof symbolLink;
	numeric: typeof numeric;
	changeBadge: typeof changeBadge;
	positive: typeof positive;
	negative: typeof negative;
	notesCell: typeof notesCell;
	notesField: typeof notesField;
	actions: typeof actions;
};
export default __default_export__;
