/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const toggleButton: string;
declare const isSecondSelectedd: string;

export {
	toggleButton,
	isSecondSelectedd
};

declare const __default_export__: {
	toggleButton: typeof toggleButton;
	isSecondSelectedd: typeof isSecondSelectedd;
};
export default __default_export__;
