/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tradingPage: string;
declare const pageHeader: string;
declare const pageTitle: string;
declare const pageSubtitle: string;

export {
	tradingPage,
	pageHeader,
	pageTitle,
	pageSubtitle
};

declare const __default_export__: {
	tradingPage: typeof tradingPage;
	pageHeader: typeof pageHeader;
	pageTitle: typeof pageTitle;
	pageSubtitle: typeof pageSubtitle;
};
export default __default_export__;
