/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const navigation: string;
declare const link: string;
declare const linkActive: string;
declare const adminWrapper: string;
declare const adminToggle: string;
declare const chev: string;
declare const adminMenu: string;
declare const adminMenuItem: string;
declare const adminMenuItemActive: string;

export {
	navigation,
	link,
	linkActive,
	adminWrapper,
	adminToggle,
	chev,
	adminMenu,
	adminMenuItem,
	adminMenuItemActive
};

declare const __default_export__: {
	navigation: typeof navigation;
	link: typeof link;
	linkActive: typeof linkActive;
	adminWrapper: typeof adminWrapper;
	adminToggle: typeof adminToggle;
	chev: typeof chev;
	adminMenu: typeof adminMenu;
	adminMenuItem: typeof adminMenuItem;
	adminMenuItemActive: typeof adminMenuItemActive;
};
export default __default_export__;
