/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const header: string;
declare const titleBlock: string;
declare const title: string;
declare const subtitle: string;
declare const headerActions: string;
declare const errorAlert: string;
declare const statsRow: string;
declare const emptyStat: string;
declare const summaryCard: string;
declare const summaryLabel: string;
declare const summaryValue: string;
declare const summarySecondary: string;
declare const tonePositive: string;
declare const toneNegative: string;
declare const metaCard: string;
declare const metaItem: string;
declare const metaItemWarn: string;
declare const metaLabel: string;
declare const metaValue: string;
declare const chartCard: string;
declare const cardTitle: string;
declare const chartWrapper: string;

export {
	container,
	header,
	titleBlock,
	title,
	subtitle,
	headerActions,
	errorAlert,
	statsRow,
	emptyStat,
	summaryCard,
	summaryLabel,
	summaryValue,
	summarySecondary,
	tonePositive,
	toneNegative,
	metaCard,
	metaItem,
	metaItemWarn,
	metaLabel,
	metaValue,
	chartCard,
	cardTitle,
	chartWrapper
};

declare const __default_export__: {
	container: typeof container;
	header: typeof header;
	titleBlock: typeof titleBlock;
	title: typeof title;
	subtitle: typeof subtitle;
	headerActions: typeof headerActions;
	errorAlert: typeof errorAlert;
	statsRow: typeof statsRow;
	emptyStat: typeof emptyStat;
	summaryCard: typeof summaryCard;
	summaryLabel: typeof summaryLabel;
	summaryValue: typeof summaryValue;
	summarySecondary: typeof summarySecondary;
	tonePositive: typeof tonePositive;
	toneNegative: typeof toneNegative;
	metaCard: typeof metaCard;
	metaItem: typeof metaItem;
	metaItemWarn: typeof metaItemWarn;
	metaLabel: typeof metaLabel;
	metaValue: typeof metaValue;
	chartCard: typeof chartCard;
	cardTitle: typeof cardTitle;
	chartWrapper: typeof chartWrapper;
};
export default __default_export__;
