/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const authPage: string;
declare const card: string;
declare const hero: string;
declare const title: string;
declare const subtitle: string;
declare const errorAlert: string;
declare const submit: string;
declare const switchLine: string;
declare const switchLink: string;

export {
	authPage,
	card,
	hero,
	title,
	subtitle,
	errorAlert,
	submit,
	switchLine,
	switchLink
};

declare const __default_export__: {
	authPage: typeof authPage;
	card: typeof card;
	hero: typeof hero;
	title: typeof title;
	subtitle: typeof subtitle;
	errorAlert: typeof errorAlert;
	submit: typeof submit;
	switchLine: typeof switchLine;
	switchLink: typeof switchLink;
};
export default __default_export__;
