/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const cryptoPriceTracker: string;
declare const error: string;
declare const titleBlock: string;
declare const title: string;
declare const subtitle: string;
declare const tradingHeader: string;
declare const searchBlock: string;
declare const searchCount: string;
declare const priceGrid: string;

export {
	cryptoPriceTracker,
	error,
	titleBlock,
	title,
	subtitle,
	tradingHeader,
	searchBlock,
	searchCount,
	priceGrid
};

declare const __default_export__: {
	cryptoPriceTracker: typeof cryptoPriceTracker;
	error: typeof error;
	titleBlock: typeof titleBlock;
	title: typeof title;
	subtitle: typeof subtitle;
	tradingHeader: typeof tradingHeader;
	searchBlock: typeof searchBlock;
	searchCount: typeof searchCount;
	priceGrid: typeof priceGrid;
};
export default __default_export__;
