/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const button: string;

export {
	button
};

declare const __default_export__: {
	button: typeof button;
};
export default __default_export__;
