/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const card: string;
declare const code: string;
declare const title: string;
declare const subtitle: string;
declare const actions: string;
declare const homeButton: string;

export {
	container,
	card,
	code,
	title,
	subtitle,
	actions,
	homeButton
};

declare const __default_export__: {
	container: typeof container;
	card: typeof card;
	code: typeof code;
	title: typeof title;
	subtitle: typeof subtitle;
	actions: typeof actions;
	homeButton: typeof homeButton;
};
export default __default_export__;
