/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const app: string;
declare const mainContent: string;

export {
	app,
	mainContent
};

declare const __default_export__: {
	app: typeof app;
	mainContent: typeof mainContent;
};
export default __default_export__;
