/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const homePage: string;
declare const hero: string;
declare const heroText: string;
declare const eyebrow: string;
declare const heroTitle: string;
declare const heroAccent: string;
declare const heroSubtitle: string;
declare const heroActions: string;
declare const heroButton: string;
declare const heroSecondaryLink: string;
declare const heroPreview: string;
declare const features: string;
declare const sectionTitle: string;
declare const featuresGrid: string;
declare const featureCard: string;
declare const featureIcon: string;
declare const featureTitle: string;
declare const featureDescription: string;

export {
	homePage,
	hero,
	heroText,
	eyebrow,
	heroTitle,
	heroAccent,
	heroSubtitle,
	heroActions,
	heroButton,
	heroSecondaryLink,
	heroPreview,
	features,
	sectionTitle,
	featuresGrid,
	featureCard,
	featureIcon,
	featureTitle,
	featureDescription
};

declare const __default_export__: {
	homePage: typeof homePage;
	hero: typeof hero;
	heroText: typeof heroText;
	eyebrow: typeof eyebrow;
	heroTitle: typeof heroTitle;
	heroAccent: typeof heroAccent;
	heroSubtitle: typeof heroSubtitle;
	heroActions: typeof heroActions;
	heroButton: typeof heroButton;
	heroSecondaryLink: typeof heroSecondaryLink;
	heroPreview: typeof heroPreview;
	features: typeof features;
	sectionTitle: typeof sectionTitle;
	featuresGrid: typeof featuresGrid;
	featureCard: typeof featureCard;
	featureIcon: typeof featureIcon;
	featureTitle: typeof featureTitle;
	featureDescription: typeof featureDescription;
};
export default __default_export__;
