/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const pageHeader: string;
declare const pageTitle: string;
declare const pageSubtitle: string;
declare const errorAlert: string;
declare const formCard: string;
declare const listCard: string;
declare const cardHeader: string;
declare const cardTitle: string;
declare const cardCount: string;
declare const editingTag: string;
declare const form: string;
declare const dateGrid: string;
declare const fieldGroup: string;
declare const fieldLabel: string;
declare const fieldHint: string;
declare const rollingTag: string;
declare const dateInput: string;
declare const endModeRow: string;
declare const modePill: string;
declare const modePillActive: string;
declare const symbolsFieldset: string;
declare const symbolsLegend: string;
declare const symbolsHint: string;
declare const symbolsGrid: string;
declare const symbolChip: string;
declare const symbolChipActive: string;
declare const formActions: string;
declare const empty: string;
declare const tableScroll: string;
declare const table: string;
declare const editingRow: string;
declare const symbolsCell: string;
declare const dateCell: string;
declare const actions: string;

export {
	container,
	pageHeader,
	pageTitle,
	pageSubtitle,
	errorAlert,
	formCard,
	listCard,
	cardHeader,
	cardTitle,
	cardCount,
	editingTag,
	form,
	dateGrid,
	fieldGroup,
	fieldLabel,
	fieldHint,
	rollingTag,
	dateInput,
	endModeRow,
	modePill,
	modePillActive,
	symbolsFieldset,
	symbolsLegend,
	symbolsHint,
	symbolsGrid,
	symbolChip,
	symbolChipActive,
	formActions,
	empty,
	tableScroll,
	table,
	editingRow,
	symbolsCell,
	dateCell,
	actions
};

declare const __default_export__: {
	container: typeof container;
	pageHeader: typeof pageHeader;
	pageTitle: typeof pageTitle;
	pageSubtitle: typeof pageSubtitle;
	errorAlert: typeof errorAlert;
	formCard: typeof formCard;
	listCard: typeof listCard;
	cardHeader: typeof cardHeader;
	cardTitle: typeof cardTitle;
	cardCount: typeof cardCount;
	editingTag: typeof editingTag;
	form: typeof form;
	dateGrid: typeof dateGrid;
	fieldGroup: typeof fieldGroup;
	fieldLabel: typeof fieldLabel;
	fieldHint: typeof fieldHint;
	rollingTag: typeof rollingTag;
	dateInput: typeof dateInput;
	endModeRow: typeof endModeRow;
	modePill: typeof modePill;
	modePillActive: typeof modePillActive;
	symbolsFieldset: typeof symbolsFieldset;
	symbolsLegend: typeof symbolsLegend;
	symbolsHint: typeof symbolsHint;
	symbolsGrid: typeof symbolsGrid;
	symbolChip: typeof symbolChip;
	symbolChipActive: typeof symbolChipActive;
	formActions: typeof formActions;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	table: typeof table;
	editingRow: typeof editingRow;
	symbolsCell: typeof symbolsCell;
	dateCell: typeof dateCell;
	actions: typeof actions;
};
export default __default_export__;
