/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const pageFooter: string;
declare const footerText: string;

export {
	pageFooter,
	footerText
};

declare const __default_export__: {
	pageFooter: typeof pageFooter;
	footerText: typeof footerText;
};
export default __default_export__;
