/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const pageHeader: string;
declare const pageTitle: string;
declare const pageSubtitle: string;
declare const errorAlert: string;
declare const notifBanner: string;
declare const notifBannerInfo: string;
declare const notifBannerOk: string;
declare const notifBannerWarn: string;
declare const formCard: string;
declare const listCard: string;
declare const cardTitle: string;
declare const cardHeader: string;
declare const summaryRow: string;
declare const summaryPill: string;
declare const summaryWatching: string;
declare const summaryTriggered: string;
declare const summaryPaused: string;
declare const addForm: string;
declare const fieldGroup: string;
declare const fieldGrow: string;
declare const fieldLabel: string;
declare const select: string;
declare const submitButton: string;
declare const empty: string;
declare const tableScroll: string;
declare const table: string;
declare const rowTriggered: string;
declare const rowInactive: string;
declare const symbolLink: string;
declare const numeric: string;
declare const statusPill: string;
declare const statusTriggered: string;
declare const statusWatching: string;
declare const statusPaused: string;
declare const actions: string;

export {
	container,
	pageHeader,
	pageTitle,
	pageSubtitle,
	errorAlert,
	notifBanner,
	notifBannerInfo,
	notifBannerOk,
	notifBannerWarn,
	formCard,
	listCard,
	cardTitle,
	cardHeader,
	summaryRow,
	summaryPill,
	summaryWatching,
	summaryTriggered,
	summaryPaused,
	addForm,
	fieldGroup,
	fieldGrow,
	fieldLabel,
	select,
	submitButton,
	empty,
	tableScroll,
	table,
	rowTriggered,
	rowInactive,
	symbolLink,
	numeric,
	statusPill,
	statusTriggered,
	statusWatching,
	statusPaused,
	actions
};

declare const __default_export__: {
	container: typeof container;
	pageHeader: typeof pageHeader;
	pageTitle: typeof pageTitle;
	pageSubtitle: typeof pageSubtitle;
	errorAlert: typeof errorAlert;
	notifBanner: typeof notifBanner;
	notifBannerInfo: typeof notifBannerInfo;
	notifBannerOk: typeof notifBannerOk;
	notifBannerWarn: typeof notifBannerWarn;
	formCard: typeof formCard;
	listCard: typeof listCard;
	cardTitle: typeof cardTitle;
	cardHeader: typeof cardHeader;
	summaryRow: typeof summaryRow;
	summaryPill: typeof summaryPill;
	summaryWatching: typeof summaryWatching;
	summaryTriggered: typeof summaryTriggered;
	summaryPaused: typeof summaryPaused;
	addForm: typeof addForm;
	fieldGroup: typeof fieldGroup;
	fieldGrow: typeof fieldGrow;
	fieldLabel: typeof fieldLabel;
	select: typeof select;
	submitButton: typeof submitButton;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	table: typeof table;
	rowTriggered: typeof rowTriggered;
	rowInactive: typeof rowInactive;
	symbolLink: typeof symbolLink;
	numeric: typeof numeric;
	statusPill: typeof statusPill;
	statusTriggered: typeof statusTriggered;
	statusWatching: typeof statusWatching;
	statusPaused: typeof statusPaused;
	actions: typeof actions;
};
export default __default_export__;
