/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tradeForm: string;
declare const tabRow: string;
declare const tab: string;
declare const tabActiveBuy: string;
declare const tabActiveSell: string;
declare const contextRow: string;
declare const contextItem: string;
declare const contextLabel: string;
declare const contextValue: string;
declare const amountField: string;
declare const amountLabel: string;
declare const amountInput: string;
declare const amountInputError: string;
declare const quickFills: string;
declare const quickFill: string;
declare const previewBlock: string;
declare const previewRow: string;
declare const errorAlert: string;
declare const successAlert: string;
declare const submitButton: string;
declare const submitBuy: string;
declare const submitSell: string;

export {
	tradeForm,
	tabRow,
	tab,
	tabActiveBuy,
	tabActiveSell,
	contextRow,
	contextItem,
	contextLabel,
	contextValue,
	amountField,
	amountLabel,
	amountInput,
	amountInputError,
	quickFills,
	quickFill,
	previewBlock,
	previewRow,
	errorAlert,
	successAlert,
	submitButton,
	submitBuy,
	submitSell
};

declare const __default_export__: {
	tradeForm: typeof tradeForm;
	tabRow: typeof tabRow;
	tab: typeof tab;
	tabActiveBuy: typeof tabActiveBuy;
	tabActiveSell: typeof tabActiveSell;
	contextRow: typeof contextRow;
	contextItem: typeof contextItem;
	contextLabel: typeof contextLabel;
	contextValue: typeof contextValue;
	amountField: typeof amountField;
	amountLabel: typeof amountLabel;
	amountInput: typeof amountInput;
	amountInputError: typeof amountInputError;
	quickFills: typeof quickFills;
	quickFill: typeof quickFill;
	previewBlock: typeof previewBlock;
	previewRow: typeof previewRow;
	errorAlert: typeof errorAlert;
	successAlert: typeof successAlert;
	submitButton: typeof submitButton;
	submitBuy: typeof submitBuy;
	submitSell: typeof submitSell;
};
export default __default_export__;
