/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const profileContainer: string;
declare const heroCard: string;
declare const heroLeft: string;
declare const heroEyebrow: string;
declare const heroAmount: string;
declare const pnlBadge: string;
declare const pnlPositive: string;
declare const pnlNegative: string;
declare const heroIdentity: string;
declare const heroEmail: string;
declare const heroActions: string;
declare const resetButton: string;
declare const resetError: string;
declare const statsRow: string;
declare const statCard: string;
declare const statLabel: string;
declare const statValue: string;
declare const holdingsCard: string;
declare const cardHeader: string;
declare const cardTitle: string;
declare const cardCount: string;
declare const empty: string;
declare const tableScroll: string;
declare const holdingsTable: string;
declare const symbolPill: string;

export {
	profileContainer,
	heroCard,
	heroLeft,
	heroEyebrow,
	heroAmount,
	pnlBadge,
	pnlPositive,
	pnlNegative,
	heroIdentity,
	heroEmail,
	heroActions,
	resetButton,
	resetError,
	statsRow,
	statCard,
	statLabel,
	statValue,
	holdingsCard,
	cardHeader,
	cardTitle,
	cardCount,
	empty,
	tableScroll,
	holdingsTable,
	symbolPill
};

declare const __default_export__: {
	profileContainer: typeof profileContainer;
	heroCard: typeof heroCard;
	heroLeft: typeof heroLeft;
	heroEyebrow: typeof heroEyebrow;
	heroAmount: typeof heroAmount;
	pnlBadge: typeof pnlBadge;
	pnlPositive: typeof pnlPositive;
	pnlNegative: typeof pnlNegative;
	heroIdentity: typeof heroIdentity;
	heroEmail: typeof heroEmail;
	heroActions: typeof heroActions;
	resetButton: typeof resetButton;
	resetError: typeof resetError;
	statsRow: typeof statsRow;
	statCard: typeof statCard;
	statLabel: typeof statLabel;
	statValue: typeof statValue;
	holdingsCard: typeof holdingsCard;
	cardHeader: typeof cardHeader;
	cardTitle: typeof cardTitle;
	cardCount: typeof cardCount;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	holdingsTable: typeof holdingsTable;
	symbolPill: typeof symbolPill;
};
export default __default_export__;
