/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const pageHeader: string;
declare const pageTitle: string;
declare const pageSubtitle: string;
declare const errorAlert: string;
declare const formCard: string;
declare const listCard: string;
declare const cardHeader: string;
declare const cardTitle: string;
declare const summaryRow: string;
declare const summaryPill: string;
declare const summaryActive: string;
declare const summaryInactive: string;
declare const form: string;
declare const grid: string;
declare const empty: string;
declare const tableScroll: string;
declare const table: string;
declare const rowInactive: string;
declare const symbolPill: string;
declare const monoCell: string;
declare const statusPill: string;
declare const statusActive: string;
declare const statusInactive: string;
declare const actions: string;

export {
	container,
	pageHeader,
	pageTitle,
	pageSubtitle,
	errorAlert,
	formCard,
	listCard,
	cardHeader,
	cardTitle,
	summaryRow,
	summaryPill,
	summaryActive,
	summaryInactive,
	form,
	grid,
	empty,
	tableScroll,
	table,
	rowInactive,
	symbolPill,
	monoCell,
	statusPill,
	statusActive,
	statusInactive,
	actions
};

declare const __default_export__: {
	container: typeof container;
	pageHeader: typeof pageHeader;
	pageTitle: typeof pageTitle;
	pageSubtitle: typeof pageSubtitle;
	errorAlert: typeof errorAlert;
	formCard: typeof formCard;
	listCard: typeof listCard;
	cardHeader: typeof cardHeader;
	cardTitle: typeof cardTitle;
	summaryRow: typeof summaryRow;
	summaryPill: typeof summaryPill;
	summaryActive: typeof summaryActive;
	summaryInactive: typeof summaryInactive;
	form: typeof form;
	grid: typeof grid;
	empty: typeof empty;
	tableScroll: typeof tableScroll;
	table: typeof table;
	rowInactive: typeof rowInactive;
	symbolPill: typeof symbolPill;
	monoCell: typeof monoCell;
	statusPill: typeof statusPill;
	statusActive: typeof statusActive;
	statusInactive: typeof statusInactive;
	actions: typeof actions;
};
export default __default_export__;
