/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const pageContainer: string;
declare const header: string;
declare const title: string;
declare const titleSymbol: string;
declare const error: string;
declare const layout: string;
declare const leftColumn: string;
declare const rightColumn: string;

export {
	pageContainer,
	header,
	title,
	titleSymbol,
	error,
	layout,
	leftColumn,
	rightColumn
};

declare const __default_export__: {
	pageContainer: typeof pageContainer;
	header: typeof header;
	title: typeof title;
	titleSymbol: typeof titleSymbol;
	error: typeof error;
	layout: typeof layout;
	leftColumn: typeof leftColumn;
	rightColumn: typeof rightColumn;
};
export default __default_export__;
