/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const brand: string;
declare const brandMark: string;
declare const brandName: string;
declare const actions: string;
declare const themeSelector: string;
declare const userBlock: string;
declare const userGreeting: string;
declare const adminBadge: string;
declare const authButtons: string;

export {
	header,
	brand,
	brandMark,
	brandName,
	actions,
	themeSelector,
	userBlock,
	userGreeting,
	adminBadge,
	authButtons
};

declare const __default_export__: {
	header: typeof header;
	brand: typeof brand;
	brandMark: typeof brandMark;
	brandName: typeof brandName;
	actions: typeof actions;
	themeSelector: typeof themeSelector;
	userBlock: typeof userBlock;
	userGreeting: typeof userGreeting;
	adminBadge: typeof adminBadge;
	authButtons: typeof authButtons;
};
export default __default_export__;
