/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const spinnerContainer: string;
declare const spinner: string;
declare const spin: string;

export {
	spinnerContainer,
	spinner,
	spin
};

declare const __default_export__: {
	spinnerContainer: typeof spinnerContainer;
	spinner: typeof spinner;
	spin: typeof spin;
};
export default __default_export__;
