/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tickerCard: string;
declare const clickable: string;
declare const cardHeader: string;
declare const symbolBlock: string;
declare const position: string;
declare const symbol: string;
declare const changeBadge: string;
declare const positive: string;
declare const negative: string;
declare const priceRow: string;
declare const price: string;
declare const changeAmount: string;
declare const positiveText: string;
declare const negativeText: string;
declare const statsRow: string;
declare const stat: string;
declare const statLabel: string;
declare const statValue: string;
declare const openHint: string;
declare const waiting: string;

export {
	tickerCard,
	clickable,
	cardHeader,
	symbolBlock,
	position,
	symbol,
	changeBadge,
	positive,
	negative,
	priceRow,
	price,
	changeAmount,
	positiveText,
	negativeText,
	statsRow,
	stat,
	statLabel,
	statValue,
	openHint,
	waiting
};

declare const __default_export__: {
	tickerCard: typeof tickerCard;
	clickable: typeof clickable;
	cardHeader: typeof cardHeader;
	symbolBlock: typeof symbolBlock;
	position: typeof position;
	symbol: typeof symbol;
	changeBadge: typeof changeBadge;
	positive: typeof positive;
	negative: typeof negative;
	priceRow: typeof priceRow;
	price: typeof price;
	changeAmount: typeof changeAmount;
	positiveText: typeof positiveText;
	negativeText: typeof negativeText;
	statsRow: typeof statsRow;
	stat: typeof stat;
	statLabel: typeof statLabel;
	statValue: typeof statValue;
	openHint: typeof openHint;
	waiting: typeof waiting;
};
export default __default_export__;
